# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class AccessMatrixLevel(BaseModel):
    """
    AccessMatrixLevel
    """
    kind: StrictStr = Field(...)
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    mode: Optional[StrictStr] = None
    model_rules: StrictInt = Field(default=..., alias="modelRules")
    blocked_routes: StrictInt = Field(default=..., alias="blockedRoutes")
    allowed_count: StrictInt = Field(default=..., alias="allowedCount")
    forbidden_count: StrictInt = Field(default=..., alias="forbiddenCount")
    bound: StrictBool = Field(...)
    __properties = ["kind", "id", "name", "mode", "modelRules", "blockedRoutes", "allowedCount", "forbiddenCount", "bound"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AccessMatrixLevel:
        """Create an instance of AccessMatrixLevel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AccessMatrixLevel:
        """Create an instance of AccessMatrixLevel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AccessMatrixLevel.parse_obj(obj)

        _obj = AccessMatrixLevel.parse_obj({
            "kind": obj.get("kind"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "mode": obj.get("mode"),
            "model_rules": obj.get("modelRules"),
            "blocked_routes": obj.get("blockedRoutes"),
            "allowed_count": obj.get("allowedCount"),
            "forbidden_count": obj.get("forbiddenCount"),
            "bound": obj.get("bound")
        })
        return _obj


