# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, validator

class AccountSurveyAnswersData(BaseModel):
    """
    AccountSurveyAnswersData
    """
    role: StrictStr = Field(...)
    use_case: StrictStr = Field(default=..., alias="useCase")
    context: StrictStr = Field(...)
    current_solution: StrictStr = Field(default=..., alias="currentSolution")
    __properties = ["role", "useCase", "context", "currentSolution"]

    @validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('backend_dev', 'ml_engineer', 'tech_lead', 'product_manager', 'learner'):
            raise ValueError("must be one of enum values ('backend_dev', 'ml_engineer', 'tech_lead', 'product_manager', 'learner')")
        return value

    @validator('use_case')
    def use_case_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('llm_in_product', 'coding_agent', 'agent_automation', 'exploring'):
            raise ValueError("must be one of enum values ('llm_in_product', 'coding_agent', 'agent_automation', 'exploring')")
        return value

    @validator('context')
    def context_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('work', 'own_product', 'hobby', 'study'):
            raise ValueError("must be one of enum values ('work', 'own_product', 'hobby', 'study')")
        return value

    @validator('current_solution')
    def current_solution_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('none', 'vpn_foreign_card', 'ru_proxy', 'self_hosted'):
            raise ValueError("must be one of enum values ('none', 'vpn_foreign_card', 'ru_proxy', 'self_hosted')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AccountSurveyAnswersData:
        """Create an instance of AccountSurveyAnswersData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AccountSurveyAnswersData:
        """Create an instance of AccountSurveyAnswersData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AccountSurveyAnswersData.parse_obj(obj)

        _obj = AccountSurveyAnswersData.parse_obj({
            "role": obj.get("role"),
            "use_case": obj.get("useCase"),
            "context": obj.get("context"),
            "current_solution": obj.get("currentSolution")
        })
        return _obj


