# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, conlist
from mlp_api.models.chat_answer_request_data import ChatAnswerRequestData

class AppendChatTurnData(BaseModel):
    """
    AppendChatTurnData
    """
    user_message: Dict[str, Any] = Field(default=..., alias="userMessage")
    answers: conlist(ChatAnswerRequestData) = Field(...)
    settings: Optional[Dict[str, Any]] = None
    __properties = ["userMessage", "answers", "settings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AppendChatTurnData:
        """Create an instance of AppendChatTurnData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in answers (list)
        _items = []
        if self.answers:
            for _item in self.answers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['answers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AppendChatTurnData:
        """Create an instance of AppendChatTurnData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AppendChatTurnData.parse_obj(obj)

        _obj = AppendChatTurnData.parse_obj({
            "user_message": obj.get("userMessage"),
            "answers": [ChatAnswerRequestData.from_dict(_item) for _item in obj.get("answers")] if obj.get("answers") is not None else None,
            "settings": obj.get("settings")
        })
        return _obj


