# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, validator

class AudioFormatOptions(BaseModel):
    """
    AudioFormatOptions
    """
    audio_encoding: Optional[StrictStr] = Field(default=None, alias="audioEncoding")
    sample_rate_hertz: Optional[StrictInt] = Field(default=None, alias="sampleRateHertz")
    chunk_size_kb: Optional[StrictInt] = Field(default=None, alias="chunkSizeKb")
    __properties = ["audioEncoding", "sampleRateHertz", "chunkSizeKb"]

    @validator('audio_encoding')
    def audio_encoding_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('LINEAR16_PCM'):
            raise ValueError("must be one of enum values ('LINEAR16_PCM')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AudioFormatOptions:
        """Create an instance of AudioFormatOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AudioFormatOptions:
        """Create an instance of AudioFormatOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AudioFormatOptions.parse_obj(obj)

        _obj = AudioFormatOptions.parse_obj({
            "audio_encoding": obj.get("audioEncoding"),
            "sample_rate_hertz": obj.get("sampleRateHertz"),
            "chunk_size_kb": obj.get("chunkSizeKb")
        })
        return _obj


