# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from mlp_api.models.catalog_api import CatalogApi
from mlp_api.models.catalog_price import CatalogPrice
from mlp_api.models.model_parameters_dto_variables_inner import ModelParametersDtoVariablesInner

class CatalogProviderOption(BaseModel):
    """
    CatalogProviderOption
    """
    id: StrictStr = Field(...)
    label: StrictStr = Field(...)
    model_id: StrictStr = Field(default=..., alias="modelId")
    route: StrictStr = Field(...)
    endpoint: StrictStr = Field(...)
    apis: conlist(CatalogApi) = Field(...)
    recommended: StrictBool = Field(...)
    cheapest: StrictBool = Field(...)
    prices: conlist(CatalogPrice) = Field(...)
    features: conlist(StrictStr) = Field(...)
    lost: conlist(StrictStr) = Field(...)
    note: Optional[StrictStr] = None
    variables: conlist(ModelParametersDtoVariablesInner) = Field(...)
    supported_params: conlist(StrictStr) = Field(default=..., alias="supportedParams")
    rf_localized: StrictBool = Field(default=..., alias="rfLocalized")
    __properties = ["id", "label", "modelId", "route", "endpoint", "apis", "recommended", "cheapest", "prices", "features", "lost", "note", "variables", "supportedParams", "rfLocalized"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CatalogProviderOption:
        """Create an instance of CatalogProviderOption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in apis (list)
        _items = []
        if self.apis:
            for _item in self.apis:
                if _item:
                    _items.append(_item.to_dict())
            _dict['apis'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in prices (list)
        _items = []
        if self.prices:
            for _item in self.prices:
                if _item:
                    _items.append(_item.to_dict())
            _dict['prices'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in variables (list)
        _items = []
        if self.variables:
            for _item in self.variables:
                if _item:
                    _items.append(_item.to_dict())
            _dict['variables'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CatalogProviderOption:
        """Create an instance of CatalogProviderOption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CatalogProviderOption.parse_obj(obj)

        _obj = CatalogProviderOption.parse_obj({
            "id": obj.get("id"),
            "label": obj.get("label"),
            "model_id": obj.get("modelId"),
            "route": obj.get("route"),
            "endpoint": obj.get("endpoint"),
            "apis": [CatalogApi.from_dict(_item) for _item in obj.get("apis")] if obj.get("apis") is not None else None,
            "recommended": obj.get("recommended"),
            "cheapest": obj.get("cheapest"),
            "prices": [CatalogPrice.from_dict(_item) for _item in obj.get("prices")] if obj.get("prices") is not None else None,
            "features": obj.get("features"),
            "lost": obj.get("lost"),
            "note": obj.get("note"),
            "variables": [ModelParametersDtoVariablesInner.from_dict(_item) for _item in obj.get("variables")] if obj.get("variables") is not None else None,
            "supported_params": obj.get("supportedParams"),
            "rf_localized": obj.get("rfLocalized")
        })
        return _obj


