# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from mlp_api.models.chat_answer_route_data import ChatAnswerRouteData

class ChatConversationSummaryData(BaseModel):
    """
    ChatConversationSummaryData
    """
    id: StrictInt = Field(...)
    title: StrictStr = Field(...)
    settings: Optional[Dict[str, Any]] = None
    archived: StrictBool = Field(...)
    created_at: datetime = Field(default=..., alias="createdAt")
    updated_at: datetime = Field(default=..., alias="updatedAt")
    last_user_preview: Optional[StrictStr] = Field(default=None, alias="lastUserPreview")
    last_answers: conlist(ChatAnswerRouteData) = Field(default=..., alias="lastAnswers")
    __properties = ["id", "title", "settings", "archived", "createdAt", "updatedAt", "lastUserPreview", "lastAnswers"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ChatConversationSummaryData:
        """Create an instance of ChatConversationSummaryData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in last_answers (list)
        _items = []
        if self.last_answers:
            for _item in self.last_answers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['lastAnswers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ChatConversationSummaryData:
        """Create an instance of ChatConversationSummaryData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ChatConversationSummaryData.parse_obj(obj)

        _obj = ChatConversationSummaryData.parse_obj({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "settings": obj.get("settings"),
            "archived": obj.get("archived"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt"),
            "last_user_preview": obj.get("lastUserPreview"),
            "last_answers": [ChatAnswerRouteData.from_dict(_item) for _item in obj.get("lastAnswers")] if obj.get("lastAnswers") is not None else None
        })
        return _obj


