# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from mlp_api.models.existing_image_data import ExistingImageData
from mlp_api.models.new_image_data import NewImageData

class ImageStepData(BaseModel):
    """
    ImageStepData
    """
    new_image: Optional[NewImageData] = Field(default=None, alias="newImage")
    existing_image: Optional[ExistingImageData] = Field(default=None, alias="existingImage")
    __properties = ["newImage", "existingImage"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ImageStepData:
        """Create an instance of ImageStepData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of new_image
        if self.new_image:
            _dict['newImage'] = self.new_image.to_dict()
        # override the default output from pydantic by calling `to_dict()` of existing_image
        if self.existing_image:
            _dict['existingImage'] = self.existing_image.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ImageStepData:
        """Create an instance of ImageStepData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ImageStepData.parse_obj(obj)

        _obj = ImageStepData.parse_obj({
            "new_image": NewImageData.from_dict(obj.get("newImage")) if obj.get("newImage") is not None else None,
            "existing_image": ExistingImageData.from_dict(obj.get("existingImage")) if obj.get("existingImage") is not None else None
        })
        return _obj


