# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from mlp_api.models.spending_limit import SpendingLimit

class InvitationKeyTemplateData(BaseModel):
    """
    InvitationKeyTemplateData
    """
    permissions: conlist(StrictStr, unique_items=True) = Field(...)
    spending_limits: conlist(SpendingLimit, unique_items=True) = Field(default=..., alias="spendingLimits")
    max_requests_per_minute: Optional[StrictInt] = Field(default=None, alias="maxRequestsPerMinute")
    ttl_seconds: Optional[StrictInt] = Field(default=None, alias="ttlSeconds")
    __properties = ["permissions", "spendingLimits", "maxRequestsPerMinute", "ttlSeconds"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InvitationKeyTemplateData:
        """Create an instance of InvitationKeyTemplateData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in spending_limits (list)
        _items = []
        if self.spending_limits:
            for _item in self.spending_limits:
                if _item:
                    _items.append(_item.to_dict())
            _dict['spendingLimits'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InvitationKeyTemplateData:
        """Create an instance of InvitationKeyTemplateData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InvitationKeyTemplateData.parse_obj(obj)

        _obj = InvitationKeyTemplateData.parse_obj({
            "permissions": obj.get("permissions"),
            "spending_limits": [SpendingLimit.from_dict(_item) for _item in obj.get("spendingLimits")] if obj.get("spendingLimits") is not None else None,
            "max_requests_per_minute": obj.get("maxRequestsPerMinute"),
            "ttl_seconds": obj.get("ttlSeconds")
        })
        return _obj


