# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class JobFailedRequest(BaseModel):
    """
    JobFailedRequest
    """
    job_id: StrictStr = Field(default=..., alias="jobId")
    job_name: StrictStr = Field(default=..., alias="jobName")
    job_owner: StrictStr = Field(default=..., alias="jobOwner")
    job_owner_id: StrictStr = Field(default=..., alias="jobOwnerId")
    exception_message: StrictStr = Field(default=..., alias="exceptionMessage")
    account_id: Optional[StrictInt] = Field(default=None, alias="accountId")
    model_id: Optional[StrictInt] = Field(default=None, alias="modelId")
    instance_id: Optional[StrictInt] = Field(default=None, alias="instanceId")
    custom_deduplication_key: Optional[StrictStr] = Field(default=None, alias="customDeduplicationKey")
    __properties = ["jobId", "jobName", "jobOwner", "jobOwnerId", "exceptionMessage", "accountId", "modelId", "instanceId", "customDeduplicationKey"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> JobFailedRequest:
        """Create an instance of JobFailedRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> JobFailedRequest:
        """Create an instance of JobFailedRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return JobFailedRequest.parse_obj(obj)

        _obj = JobFailedRequest.parse_obj({
            "job_id": obj.get("jobId"),
            "job_name": obj.get("jobName"),
            "job_owner": obj.get("jobOwner"),
            "job_owner_id": obj.get("jobOwnerId"),
            "exception_message": obj.get("exceptionMessage"),
            "account_id": obj.get("accountId"),
            "model_id": obj.get("modelId"),
            "instance_id": obj.get("instanceId"),
            "custom_deduplication_key": obj.get("customDeduplicationKey")
        })
        return _obj


