# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class LimitNotificationRequest(BaseModel):
    """
    LimitNotificationRequest
    """
    limit_type: StrictStr = Field(default=..., alias="limitType")
    token_id: Optional[StrictInt] = Field(default=None, alias="tokenId")
    token_name: Optional[StrictStr] = Field(default=None, alias="tokenName")
    available: Union[StrictFloat, StrictInt] = Field(...)
    limit: Union[StrictFloat, StrictInt] = Field(...)
    available_percent: Union[StrictFloat, StrictInt] = Field(default=..., alias="availablePercent")
    interval: StrictStr = Field(...)
    __properties = ["limitType", "tokenId", "tokenName", "available", "limit", "availablePercent", "interval"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LimitNotificationRequest:
        """Create an instance of LimitNotificationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LimitNotificationRequest:
        """Create an instance of LimitNotificationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LimitNotificationRequest.parse_obj(obj)

        _obj = LimitNotificationRequest.parse_obj({
            "limit_type": obj.get("limitType"),
            "token_id": obj.get("tokenId"),
            "token_name": obj.get("tokenName"),
            "available": obj.get("available"),
            "limit": obj.get("limit"),
            "available_percent": obj.get("availablePercent"),
            "interval": obj.get("interval")
        })
        return _obj


