# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, constr

class LlmProviderData(BaseModel):
    """
    LlmProviderData
    """
    name: constr(strict=True, max_length=100, min_length=0) = Field(...)
    display_name: constr(strict=True, max_length=100, min_length=0) = Field(default=..., alias="displayName")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    __properties = ["name", "displayName", "createdAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LlmProviderData:
        """Create an instance of LlmProviderData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LlmProviderData:
        """Create an instance of LlmProviderData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LlmProviderData.parse_obj(obj)

        _obj = LlmProviderData.parse_obj({
            "name": obj.get("name"),
            "display_name": obj.get("displayName"),
            "created_at": obj.get("createdAt")
        })
        return _obj


