# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from mlp_api.models.model_instance_data import ModelInstanceData

class ModelInstanceListData(BaseModel):
    """
    ModelInstanceListData
    """
    instances: conlist(ModelInstanceData) = Field(...)
    __properties = ["instances"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ModelInstanceListData:
        """Create an instance of ModelInstanceListData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in instances (list)
        _items = []
        if self.instances:
            for _item in self.instances:
                if _item:
                    _items.append(_item.to_dict())
            _dict['instances'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ModelInstanceListData:
        """Create an instance of ModelInstanceListData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ModelInstanceListData.parse_obj(obj)

        _obj = ModelInstanceListData.parse_obj({
            "instances": [ModelInstanceData.from_dict(_item) for _item in obj.get("instances")] if obj.get("instances") is not None else None
        })
        return _obj


