# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, validator

class ModelTypeStepData(BaseModel):
    """
    ModelTypeStepData
    """
    model_type: StrictStr = Field(default=..., alias="modelType")
    enable_http_interface: Optional[StrictBool] = Field(default=None, alias="enableHttpInterface")
    __properties = ["modelType", "enableHttpInterface"]

    @validator('model_type')
    def model_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('MLP_SERVICE', 'WEB_APPLICATION', 'MCP_SERVER'):
            raise ValueError("must be one of enum values ('MLP_SERVICE', 'WEB_APPLICATION', 'MCP_SERVER')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ModelTypeStepData:
        """Create an instance of ModelTypeStepData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ModelTypeStepData:
        """Create an instance of ModelTypeStepData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ModelTypeStepData.parse_obj(obj)

        _obj = ModelTypeStepData.parse_obj({
            "model_type": obj.get("modelType"),
            "enable_http_interface": obj.get("enableHttpInterface")
        })
        return _obj


