# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt

class ModelAutoScalingConfiguration(BaseModel):
    """
    ModelAutoScalingConfiguration
    """
    min_instance_count: StrictInt = Field(default=..., alias="minInstanceCount")
    max_instance_count: Optional[StrictInt] = Field(default=None, alias="maxInstanceCount")
    cooldown_duration_minutes: Optional[StrictInt] = Field(default=None, alias="cooldownDurationMinutes")
    scale_up_requests_per_minute_threshold: Optional[StrictInt] = Field(default=None, alias="scaleUpRequestsPerMinuteThreshold")
    scale_down_requests_per_minute_threshold: Optional[StrictInt] = Field(default=None, alias="scaleDownRequestsPerMinuteThreshold")
    scale_up_latency_threshold_ms: Optional[StrictInt] = Field(default=None, alias="scaleUpLatencyThresholdMs")
    scale_down_latency_threshold_ms: Optional[StrictInt] = Field(default=None, alias="scaleDownLatencyThresholdMs")
    scale_up_cpu_threshold_milli_cores: Optional[StrictInt] = Field(default=None, alias="scaleUpCpuThresholdMilliCores")
    scale_down_cpu_threshold_milli_cores: Optional[StrictInt] = Field(default=None, alias="scaleDownCpuThresholdMilliCores")
    active: StrictBool = Field(...)
    __properties = ["minInstanceCount", "maxInstanceCount", "cooldownDurationMinutes", "scaleUpRequestsPerMinuteThreshold", "scaleDownRequestsPerMinuteThreshold", "scaleUpLatencyThresholdMs", "scaleDownLatencyThresholdMs", "scaleUpCpuThresholdMilliCores", "scaleDownCpuThresholdMilliCores", "active"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ModelAutoScalingConfiguration:
        """Create an instance of ModelAutoScalingConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ModelAutoScalingConfiguration:
        """Create an instance of ModelAutoScalingConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ModelAutoScalingConfiguration.parse_obj(obj)

        _obj = ModelAutoScalingConfiguration.parse_obj({
            "min_instance_count": obj.get("minInstanceCount"),
            "max_instance_count": obj.get("maxInstanceCount"),
            "cooldown_duration_minutes": obj.get("cooldownDurationMinutes"),
            "scale_up_requests_per_minute_threshold": obj.get("scaleUpRequestsPerMinuteThreshold"),
            "scale_down_requests_per_minute_threshold": obj.get("scaleDownRequestsPerMinuteThreshold"),
            "scale_up_latency_threshold_ms": obj.get("scaleUpLatencyThresholdMs"),
            "scale_down_latency_threshold_ms": obj.get("scaleDownLatencyThresholdMs"),
            "scale_up_cpu_threshold_milli_cores": obj.get("scaleUpCpuThresholdMilliCores"),
            "scale_down_cpu_threshold_milli_cores": obj.get("scaleDownCpuThresholdMilliCores"),
            "active": obj.get("active")
        })
        return _obj


