# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from mlp_api.models.boolean_constant import BooleanConstant
from mlp_api.models.enum_constant import EnumConstant
from mlp_api.models.integer_constant import IntegerConstant
from mlp_api.models.number_constant import NumberConstant
from mlp_api.models.string_constant import StringConstant
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

MODELPARAMETERSDTOCONSTANTSINNER_ONE_OF_SCHEMAS = ["BooleanConstant", "EnumConstant", "IntegerConstant", "NumberConstant", "StringConstant"]

class ModelParametersDtoConstantsInner(BaseModel):
    """
    ModelParametersDtoConstantsInner
    """
    # data type: BooleanConstant
    oneof_schema_1_validator: Optional[BooleanConstant] = None
    # data type: EnumConstant
    oneof_schema_2_validator: Optional[EnumConstant] = None
    # data type: IntegerConstant
    oneof_schema_3_validator: Optional[IntegerConstant] = None
    # data type: NumberConstant
    oneof_schema_4_validator: Optional[NumberConstant] = None
    # data type: StringConstant
    oneof_schema_5_validator: Optional[StringConstant] = None
    if TYPE_CHECKING:
        actual_instance: Union[BooleanConstant, EnumConstant, IntegerConstant, NumberConstant, StringConstant]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(MODELPARAMETERSDTOCONSTANTSINNER_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    discriminator_value_class_map = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ModelParametersDtoConstantsInner.construct()
        error_messages = []
        match = 0
        # validate data type: BooleanConstant
        if not isinstance(v, BooleanConstant):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BooleanConstant`")
        else:
            match += 1
        # validate data type: EnumConstant
        if not isinstance(v, EnumConstant):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnumConstant`")
        else:
            match += 1
        # validate data type: IntegerConstant
        if not isinstance(v, IntegerConstant):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IntegerConstant`")
        else:
            match += 1
        # validate data type: NumberConstant
        if not isinstance(v, NumberConstant):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NumberConstant`")
        else:
            match += 1
        # validate data type: StringConstant
        if not isinstance(v, StringConstant):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StringConstant`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ModelParametersDtoConstantsInner with oneOf schemas: BooleanConstant, EnumConstant, IntegerConstant, NumberConstant, StringConstant. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ModelParametersDtoConstantsInner with oneOf schemas: BooleanConstant, EnumConstant, IntegerConstant, NumberConstant, StringConstant. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> ModelParametersDtoConstantsInner:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> ModelParametersDtoConstantsInner:
        """Returns the object represented by the json string"""
        instance = ModelParametersDtoConstantsInner.construct()
        error_messages = []
        match = 0

        # deserialize data into BooleanConstant
        try:
            instance.actual_instance = BooleanConstant.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EnumConstant
        try:
            instance.actual_instance = EnumConstant.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IntegerConstant
        try:
            instance.actual_instance = IntegerConstant.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NumberConstant
        try:
            instance.actual_instance = NumberConstant.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StringConstant
        try:
            instance.actual_instance = StringConstant.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ModelParametersDtoConstantsInner with oneOf schemas: BooleanConstant, EnumConstant, IntegerConstant, NumberConstant, StringConstant. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ModelParametersDtoConstantsInner with oneOf schemas: BooleanConstant, EnumConstant, IntegerConstant, NumberConstant, StringConstant. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


