# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import Field, StrictFloat, StrictInt
from mlp_api.models.applies_to import AppliesTo
from mlp_api.models.client_discount import ClientDiscount

class MultiplyClientDiscount(ClientDiscount):
    """
    MultiplyClientDiscount
    """
    multiplier: Union[StrictFloat, StrictInt] = Field(...)
    applies_to: AppliesTo = Field(default=..., alias="appliesTo")
    __properties = ["clientIds", "type", "multiplier", "appliesTo"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MultiplyClientDiscount:
        """Create an instance of MultiplyClientDiscount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of applies_to
        if self.applies_to:
            _dict['appliesTo'] = self.applies_to.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MultiplyClientDiscount:
        """Create an instance of MultiplyClientDiscount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MultiplyClientDiscount.parse_obj(obj)

        _obj = MultiplyClientDiscount.parse_obj({
            "client_ids": obj.get("clientIds"),
            "type": obj.get("type"),
            "multiplier": obj.get("multiplier"),
            "applies_to": AppliesTo.from_dict(obj.get("appliesTo")) if obj.get("appliesTo") is not None else None
        })
        return _obj


