# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator

class RateMetric(BaseModel):
    """
    RateMetric
    """
    role: StrictStr = Field(...)
    unit: StrictStr = Field(...)
    qualifier: Optional[StrictStr] = None
    __properties = ["role", "unit", "qualifier"]

    @validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('input', 'cacheRead', 'cacheWrite', 'output', 'request'):
            raise ValueError("must be one of enum values ('input', 'cacheRead', 'cacheWrite', 'output', 'request')")
        return value

    @validator('unit')
    def unit_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('tokens', 'seconds', 'calls', 'units'):
            raise ValueError("must be one of enum values ('tokens', 'seconds', 'calls', 'units')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RateMetric:
        """Create an instance of RateMetric from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RateMetric:
        """Create an instance of RateMetric from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RateMetric.parse_obj(obj)

        _obj = RateMetric.parse_obj({
            "role": obj.get("role"),
            "unit": obj.get("unit"),
            "qualifier": obj.get("qualifier")
        })
        return _obj


