# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictStr, conlist

class ServerCapacityData(BaseModel):
    """
    ServerCapacityData
    """
    cpu: StrictStr = Field(...)
    memory: StrictStr = Field(...)
    disk: StrictStr = Field(...)
    gpu_models: conlist(StrictStr) = Field(default=..., alias="gpuModels")
    __properties = ["cpu", "memory", "disk", "gpuModels"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServerCapacityData:
        """Create an instance of ServerCapacityData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServerCapacityData:
        """Create an instance of ServerCapacityData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServerCapacityData.parse_obj(obj)

        _obj = ServerCapacityData.parse_obj({
            "cpu": obj.get("cpu"),
            "memory": obj.get("memory"),
            "disk": obj.get("disk"),
            "gpu_models": obj.get("gpuModels")
        })
        return _obj


