# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from mlp_api.paths.api_mlpgate_system_config_captcha.get import GetCaptchaConfig
from mlp_api.paths.api_mlpgate_system_config_dataset_data_type.get import GetDatasetDataTypes
from mlp_api.paths.api_mlpgate_system_config_model_defaults.get import GetModelDefaults
from mlp_api.paths.api_mlpgate_system_config_resource_groups.get import GetResourceGroupsForAccount
from mlp_api.paths.api_mlpgate_system_config_task_types.get import GetTaskTypes


class SystemConfigEndpointApi(
    GetCaptchaConfig,
    GetDatasetDataTypes,
    GetModelDefaults,
    GetResourceGroupsForAccount,
    GetTaskTypes,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
