stages:
  - build
  - deploy


build:
  stage: build
  script:
    - make generate test

deploy:
  stage: deploy
  needs:
    - build
  script:
    - make build deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "v2"
      when: always
