stages:
  - build
  - deploy

build:
  stage: build
  image: python:3.12-slim
  services:
    - docker:24.0.5-dind
  tags:
    - docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  before_script:
    - echo "machine nexus.just-ai.com" > ~/.netrc
    - echo "login $NEXUS_USER" >> ~/.netrc
    - echo "password $NEXUS_PASSWORD" >> ~/.netrc
    - cat ~/.netrc
    - apt-get update && apt-get -y install make
    - apt-get update && apt-get -y --no-install-recommends install bash docker-cli docker-buildx libatomic1
    - pip install uv
    - make venv
  script:
    - make generate test

deploy:
  stage: deploy
  needs:
    - build
  script:
    - make build deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "v2"
      when: always
