stages:
  - generate
  - build

generate:
  stage: generate
  script:
    - sh ./build-scripts/generate-rest.sh
    - sh ./build-scripts/generate-grpc.sh

job_build:
  stage: build
  script:
    - sh ./build.sh $CI_COMMIT_REF_NAME

