repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: format
        name: Ruff format and fix
        language: system
        pass_filenames: false
        always_run: true
        entry: make check

  - repo: local
    hooks:
      - id: bump-version
        name: Update version
        language: system
        pass_filenames: false
        always_run: true
        entry: make bump_version
