[project]
name = "mlp-python-sdk"
version = "2.0.0-a"
requires-python = "==3.12.*"
dependencies = [
    "dacite>=1.9.2",
    "graypy>=2.1.0",
    "grpcio==1.71.0",
    "jsonpath-ng>=1.7.0",
    "more-itertools>=10.6.0",
    "protobuf==5.29.4",
    "pydantic>=2.11.1",
    "python-box>=7.3.2",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.0",
    "pyright>=1.1.397",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "pytest-html>=4.1.1",
    "grpc-stubs>=1.53.0.5",
    "numpy>=2.2.4",
    "grpcio-tools==1.71.0",
]

[tool.ruff]
line-length = 160
target-version = "py313"
exclude = [
    "src/mlp_sdk/mlp_connector/grpc_/*.py*",
]

[tool.ruff.lint]
select = [
    "E",       # pycodestyle (error)
    "F",       # pyflakes
    "W",       # pycodestyle (warning)
    "B",       # flake8-bugbear
    "I",       # isort
    "C4",      # flake8-comprehensions
    "SIM201", "SIM202",  # simplify comparisons involving not
    "RET501", "RET502",  # better return None handling,
]
ignore = [
#    "PGH004",  # Unused blanket `noqa` directive
#    "ISC001",  # implicitly concatenated string
#    "UP",      # pyupgrade
]
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.pytest.ini_options]
# тесты должны запускаться с текущей папкой в ./tests
pythonpath = ["./src", "./tests"]
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
log_cli = true
log_cli_level = "DEBUG"
addopts = "--cov=../src --cov-report=term --cov-report=html:../htmlcov --html=../pytest-report/index.html"

[tool.pyright]
venvPath = "."
venv = ".venv"
#typeCheckingMode = "strict"
exclude = [
    "src/mlp_sdk/mlp_connector/grpc_/*.py*",
]
include =  [
    "src"
]
