[project]
name = "mlp-sdk"
version = "2.3.0"
requires-python = ">=3.10"
authors = []
description = "Python library for creating services for mlp"
dependencies = [
    "dacite>=1.9.2",
    "graypy>=2.1.0",
    "grpcio>=1.71.0",
    "more-itertools>=10.6.0",
    "protobuf>=5.29.4",
    "pydantic>=2.11.1",
    "python-box>=7.3.2",
    "python-dateutil>=2.9.0.post0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.0",
    "pyright>=1.1.397",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "pytest-html>=4.1.1",
    "grpc-stubs>=1.53.0.5",
    "numpy>=2.2.4",
    "grpcio-tools>=1.71.0",
    "build>=1.2.2.post1",
    "twine>=6.1.0",
    "tomli>=2.2.1",
    "tomli-w>=1.2.0",
    "pre-commit>=4.2.0",
]

[tool.uv]
index = [
    { name = "nexus-open", url = "https://nexus-open.just-ai.com/repository/pypi-hosted/simple" },
    { name = "nexus-private", url = "https://nexus.just-ai.com/repository/pypi-hosted/simple" },
]

[tool.ruff]
line-length = 160
target-version = "py313"
src = [
    "src",
    "tests",
]
exclude = [
    "src/mlp_sdk/mlp_connector/grpc_/*.py*",
    "src/mlp_sdk/mlp_api/**",
    "src/mlp_sdk/storage_api/**",
]
include = [
    "src/**/*.py",
    "tests/**/*.py",
    "examples/**/*.py",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "B",
    "I",
    "C4",
    "SIM201",
    "SIM202",
    "RET501",
    "RET502",
]
ignore = []
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.pytest.ini_options]
pythonpath = [
    "./src",
    "./tests",
]
testpaths = [
    "tests",
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
log_cli = true
log_cli_level = "DEBUG"
addopts = "--cov=../src --cov-report=term --cov-report=html:../htmlcov --html=../pytest-report/index.html"

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [
    "src/mlp_sdk/mlp_connector/grpc_/*.py*",
    "src/mlp_sdk/mlp_api/**",
    "src/mlp_sdk/storage_api/**",
    "src/mlp_sdk/storage/*",
]
include = [
    "src",
]

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"
