[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "venv",
    "dist",
    "build",
    ".pyenv-opt-venv-3.8-3.8.6-bin-python",
    ".pyenv-opt-python3.10-virtualenv-bin-python",
    "mlp_api",
    "mlp_sdk/grpc",
]

line-length = 120
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = [
    "src",
    "tests",
    "mlp_sdk",
    "caila_sts",
]

[tool.ruff.lint]
select = [
    "E",       # pycodestyle (error)
    "F",       # pyflakes
    "W",       # pycodestyle (warning)
    "B",       # flake8-bugbear
    "I",       # isort
    "C4",      # flake8-comprehensions
    "SIM201", "SIM202",  # simplify comparisons involving not
    "RET501", "RET502",  # better return None handling,
]

ignore = [
    "PGH004",  # Unused blanket `noqa` directive
    "ISC001",  # implicitly concatenated string
    "UP",      # pyupgrade
]
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"
