# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from mlp_api import schemas  # noqa: F401


class ModelAliasData(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "aliases",
            "id",
        }
        
        class properties:
        
            @staticmethod
            def id() -> typing.Type['ModelInfoPK']:
                return ModelInfoPK
            
            
            class aliases(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AliasData']:
                        return AliasData
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['AliasData'], typing.List['AliasData']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'aliases':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AliasData':
                    return super().__getitem__(i)
            __annotations__ = {
                "id": id,
                "aliases": aliases,
            }
    
    aliases: MetaOapg.properties.aliases
    id: 'ModelInfoPK'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> 'ModelInfoPK': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["aliases"]) -> MetaOapg.properties.aliases: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "aliases", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> 'ModelInfoPK': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["aliases"]) -> MetaOapg.properties.aliases: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "aliases", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        aliases: typing.Union[MetaOapg.properties.aliases, list, tuple, ],
        id: 'ModelInfoPK',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelAliasData':
        return super().__new__(
            cls,
            *_args,
            aliases=aliases,
            id=id,
            _configuration=_configuration,
            **kwargs,
        )

from mlp_api.model.alias_data import AliasData
from mlp_api.model.model_info_pk import ModelInfoPK
