# flake8: noqa

# import apis into api package
from mlp_api.api.access_token_endpoint_api import AccessTokenEndpointApi
from mlp_api.api.account_endpoint_api import AccountEndpointApi
from mlp_api.api.admin_endpoint_api import AdminEndpointApi
from mlp_api.api.application_endpoint_api import ApplicationEndpointApi
from mlp_api.api.click_history_endpoint_api import ClickHistoryEndpointApi
from mlp_api.api.data_image_endpoint_api import DataImageEndpointApi
from mlp_api.api.dataset_endpoint_api import DatasetEndpointApi
from mlp_api.api.fit_config_endpoint_api import FitConfigEndpointApi
from mlp_api.api.image_endpoint_api import ImageEndpointApi
from mlp_api.api.internal_endpoint_api import InternalEndpointApi
from mlp_api.api.job_endpoint_api import JobEndpointApi
from mlp_api.api.manual_management_endpoint_api import ManualManagementEndpointApi
from mlp_api.api.metric_endpoint_api import MetricEndpointApi
from mlp_api.api.model_alias_endpoint_api import ModelAliasEndpointApi
from mlp_api.api.model_endpoint_api import ModelEndpointApi
from mlp_api.api.model_group_endpoint_api import ModelGroupEndpointApi
from mlp_api.api.model_instance_endpoint_api import ModelInstanceEndpointApi
from mlp_api.api.predict_config_endpoint_api import PredictConfigEndpointApi
from mlp_api.api.process_endpoint_api import ProcessEndpointApi
from mlp_api.api.resource_group_endpoint_api import ResourceGroupEndpointApi
from mlp_api.api.resource_group_quota_endpoint_api import ResourceGroupQuotaEndpointApi
from mlp_api.api.resource_group_servers_endpoint_api import ResourceGroupServersEndpointApi
from mlp_api.api.specs_endpoint_api import SpecsEndpointApi
from mlp_api.api.stat_log_endpoint_api import StatLogEndpointApi
from mlp_api.api.system_config_endpoint_api import SystemConfigEndpointApi
from mlp_api.api.system_endpoint_api import SystemEndpointApi
from mlp_api.api.task_endpoint_api import TaskEndpointApi

