# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from caila_api.paths.api_cailagate_account_dump_account_id.get import DumpConfig
from caila_api.paths.api_cailagate_account.get import EnsureAccount
from caila_api.paths.api_cailagate_account_s3_account_id.get import GetS3Credentials
from caila_api.paths.api_cailagate_account_dump_account_id.post import RestoreConfig
from caila_api.paths.api_cailagate_account.post import UpdateAccountData


class AccountEndpointApi(
    DumpConfig,
    EnsureAccount,
    GetS3Credentials,
    RestoreConfig,
    UpdateAccountData,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
