# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from caila_api.paths.api_cailagate_account_account_id_model_model_id_external.post import CreateExternalConnection
from caila_api.paths.api_cailagate_account_account_id_model.post import CreateModel
from caila_api.paths.api_cailagate_account_account_id_model_model_id_external.delete import DeleteExternalConnection
from caila_api.paths.api_cailagate_account_account_id_model_model_id.delete import DeleteModel
from caila_api.paths.api_cailagate_account_account_id_model_model_id_external.get import GetExternalConnectionInfo
from caila_api.paths.api_cailagate_account_account_id_model_model_id_instances.get import GetInstancesStatus
from caila_api.paths.api_cailagate_account_account_id_model_model_id_logs.get import GetLogsByModel
from caila_api.paths.api_cailagate_account_account_id_model_model_id.get import GetModelInfo
from caila_api.paths.api_cailagate_account_account_id_model.get import GetPagedModels
from caila_api.paths.api_cailagate_account_account_id_model_model_id_simple_doc.get import GetSimpleDoc
from caila_api.paths.api_cailagate_account_account_id_model_model_id_last_job.get import LastJob
from caila_api.paths.api_cailagate_account_account_id_model_model_id_instances.post import SetRequestedInstancesCount
from caila_api.paths.api_cailagate_account_account_id_model_model_id_simple_doc.post import SetSimpleDoc
from caila_api.paths.api_cailagate_account_account_id_model_model_id_status.get import ShortModelStatus
from caila_api.paths.api_cailagate_account_account_id_model_model_id_instance_start.post import StartNewInstance
from caila_api.paths.api_cailagate_account_account_id_model_model_id.post import UpdateModel


class ModelEndpointApi(
    CreateExternalConnection,
    CreateModel,
    DeleteExternalConnection,
    DeleteModel,
    GetExternalConnectionInfo,
    GetInstancesStatus,
    GetLogsByModel,
    GetModelInfo,
    GetPagedModels,
    GetSimpleDoc,
    LastJob,
    SetRequestedInstancesCount,
    SetSimpleDoc,
    ShortModelStatus,
    StartNewInstance,
    UpdateModel,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
