# coding: utf-8

# flake8: noqa

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from mpl_api.api_client import ApiClient

# import Configuration
from mpl_api.configuration import Configuration

# import exceptions
from mpl_api.exceptions import OpenApiException
from mpl_api.exceptions import ApiAttributeError
from mpl_api.exceptions import ApiTypeError
from mpl_api.exceptions import ApiValueError
from mpl_api.exceptions import ApiKeyError
from mpl_api.exceptions import ApiException
