# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from mpl_api.paths.api_mplgate_account_account_id_model_model_id_fit_config.post import CreateFitConfig
from mpl_api.paths.api_mplgate_account_account_id_model_model_id_fit_config_config_id.delete import DeleteFitConfig
from mpl_api.paths.api_mplgate_account_account_id_model_model_id_fit_config_config_id.get import GetFitConfig
from mpl_api.paths.api_mplgate_account_account_id_model_model_id_fit_config.get import ListFitConfigs
from mpl_api.paths.api_mplgate_account_account_id_model_model_id_fit_config_config_id.post import UpdateFitConfig


class FitConfigEndpointApi(
    CreateFitConfig,
    DeleteFitConfig,
    GetFitConfig,
    ListFitConfigs,
    UpdateFitConfig,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
