# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from mpl_api.paths.api_mplgate_account_account_id_image.post import CreateImage
from mpl_api.paths.api_mplgate_account_account_id_image_image_id.delete import DeleteImage
from mpl_api.paths.api_mplgate_account_account_id_image_image_id.get import GetImage
from mpl_api.paths.api_mplgate_account_account_id_image_image_id_logs.get import GetLogsByImage
from mpl_api.paths.api_mplgate_account_account_id_image.get import GetPagedImages
from mpl_api.paths.api_mplgate_account_account_id_image_image_id.post import UpdateImage


class ImageEndpointApi(
    CreateImage,
    DeleteImage,
    GetImage,
    GetLogsByImage,
    GetPagedImages,
    UpdateImage,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
